---
# vars file for common
#
cumulususers:
  - cumulus
snmppass: snmp123
defaultntp:
  - 0.cumulusnetworks.pool.ntp.org
  - 1.cumulusnetworks.pool.ntp.org
  - 2.cumulusnetworks.pool.ntp.org
  - 3.cumulusnetworks.pool.ntp.org

ntpservers:
 - 0.bham.ntp.org
 - 1.bham.ntp.org
 - 2.bham.ntp.org
 - 3.bham.ntp.org

syslogservers:
  - 10.20.0.50
  - 10.20.0.51
  - 10.20.0.52
